# Generated by Django 5.2.3 on 2025-06-13 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Compagnies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('pays_ratt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='avions/')),
                ('longueur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pistes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('longueur', models.IntegerField()),
                ('aeroports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avion.aeroports')),
            ],
        ),
        migrations.CreateModel(
            name='Avions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avion.compagnies')),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avion.types')),
            ],
        ),
        migrations.CreateModel(
            name='Vols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilote', models.CharField(max_length=100)),
                ('h_dep', models.DateTimeField()),
                ('h_arr', models.DateTimeField()),
                ('aeroports_arr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols_arrivee', to='avion.aeroports')),
                ('aeroports_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vols_depart', to='avion.aeroports')),
                ('avions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='avion.avions')),
            ],
        ),
    ]
