# Generated by Django 5.2.3 on 2025-06-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areoports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Avions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('compagnie', models.CharField(blank=True)),
                ('modele', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Compagnies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True)),
                ('pays_ratt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pistes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('areoports', models.CharField(max_length=100)),
                ('longueur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('longueur', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avions', models.CharField(max_length=100)),
                ('pilote', models.CharField(max_length=100)),
                ('areoports_dep', models.CharField(max_length=100)),
                ('h_dep', models.DateTimeField()),
                ('areoports_arr', models.CharField(max_length=100)),
                ('h_arr', models.DateTimeField()),
            ],
        ),
    ]
